.TH "C:/Users/ledio_000/Documents/GitHub/CS340/Fotoshop Directory Reference" 3 "Sat Nov 30 2013" "Fotoshop" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/ledio_000/Documents/GitHub/CS340/Fotoshop Directory Reference \- 
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBdarkroom\&.cpp\fP"
.br
.ti -1c
.RI "file \fBdarkroom\&.h\fP"
.br
.ti -1c
.RI "file \fBfilters\&.cpp\fP"
.br
.RI "\fIC++ code for all of the filter algorithms called in the work area\&. \fP"
.ti -1c
.RI "file \fBfilters\&.h\fP"
.br
.ti -1c
.RI "file \fBincludes\&.h\fP"
.br
.ti -1c
.RI "file \fBmain\&.cpp\fP"
.br
.RI "\fImain Cpp file for program \fP"
.ti -1c
.RI "file \fBmainwindow\&.cpp\fP"
.br
.RI "\fIholds the code that is initially run to output the first GUI window \fP"
.ti -1c
.RI "file \fBmainwindow\&.h\fP"
.br
.ti -1c
.RI "file \fBUndoArray\&.cpp\fP"
.br
.ti -1c
.RI "file \fBworkingwindow\&.cpp\fP"
.br
.ti -1c
.RI "file \fBworkingwindow\&.h\fP"
.br
.in -1c
