.TH "C:/Users/ledio_000/Documents/GitHub/CS340/Fotoshop/darkroom.h" 3 "Sat Nov 30 2013" "Fotoshop" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/ledio_000/Documents/GitHub/CS340/Fotoshop/darkroom.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'includes\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBpaintBucket\fP (int x, int y, QColor toPaint, QColor desiredColor)"
.br
.ti -1c
.RI "void \fBdoBucket\fP (QPoint colorStart)"
.br
.ti -1c
.RI "void \fBsaturate\fP ()"
.br
.ti -1c
.RI "void \fBdesaturate\fP ()"
.br
.ti -1c
.RI "void \fBwarm\fP ()"
.br
.ti -1c
.RI "void \fBcool\fP ()"
.br
.RI "\fIvoid cool \fP"
.ti -1c
.RI "void \fBoverExpose\fP ()"
.br
.ti -1c
.RI "void \fBunderExpose\fP ()"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "void cool ()"

.PP
void cool Function to cool the image, takes 0 parameters
.PP
function that changes the image white balance to cooler 
.PP
Definition at line 98 of file darkroom\&.cpp\&.
.SS "void desaturate ()"
Function to desaturate the image, takes 0 parameters 
.PP
Definition at line 39 of file darkroom\&.cpp\&.
.SS "void doBucket (QPointcolorStart)"
Function to initialize paint bucket 
.PP
Definition at line 185 of file darkroom\&.cpp\&.
.SS "void overExpose ()"
Function to raise exposure, takes 0 parameters 
.PP
Definition at line 120 of file darkroom\&.cpp\&.
.SS "int paintBucket (intx, inty, QColortoPaint, QColordesiredColor)"
DARKROOM Header File function constructors for the Darkroom set of tools\&. Floodfill function 
.PP
Definition at line 198 of file darkroom\&.cpp\&.
.SS "void saturate ()"
Function to saturate the image, takes 0 parameters 
.PP
Definition at line 7 of file darkroom\&.cpp\&.
.SS "void underExpose ()"
Function to lower exposure, takes 0 parameters 
.PP
Definition at line 153 of file darkroom\&.cpp\&.
.SS "void warm ()"
Function to warm the image, takes 0 parameters 
.PP
Definition at line 72 of file darkroom\&.cpp\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Fotoshop from the source code\&.
