.TH "C:/Users/ledio_000/Documents/GitHub/CS340/Fotoshop/filters.h" 3 "Sat Nov 30 2013" "Fotoshop" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/ledio_000/Documents/GitHub/CS340/Fotoshop/filters.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'includes\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "QImage \fBgreyscale\fP (QImage image)"
.br
.ti -1c
.RI "QImage \fBpencil\fP (QImage image)"
.br
.ti -1c
.RI "QImage \fBnegative\fP (QImage image)"
.br
.ti -1c
.RI "QImage \fBBoost\fP (QImage image)"
.br
.ti -1c
.RI "QImage \fBsepia\fP (QImage image)"
.br
.ti -1c
.RI "QImage \fBedgeDetect\fP (QImage image)"
.br
.ti -1c
.RI "QImage \fBpixelate\fP (QImage image)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "QImage Boost (QImageimage)"

.PP
Definition at line 42 of file filters\&.cpp\&.
.SS "QImage edgeDetect (QImageimage)"

.PP
Definition at line 123 of file filters\&.cpp\&.
.SS "QImage greyscale (QImageimage)"
Header for the photofilters 
.PP
Definition at line 4 of file filters\&.cpp\&.
.SS "QImage negative (QImageimage)"

.PP
Definition at line 84 of file filters\&.cpp\&.
.SS "QImage pencil (QImageimage)"

.PP
Definition at line 20 of file filters\&.cpp\&.
.SS "QImage pixelate (QImageimage)"

.PP
Definition at line 150 of file filters\&.cpp\&.
.SS "QImage sepia (QImageimage)"

.PP
Definition at line 103 of file filters\&.cpp\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Fotoshop from the source code\&.
