.TH "C:/Users/ledio_000/Documents/GitHub/CS340/Fotoshop/includes.h" 3 "Sat Nov 30 2013" "Fotoshop" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/ledio_000/Documents/GitHub/CS340/Fotoshop/includes.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <QFileDialog>\fP
.br
\fC#include <stdlib\&.h>\fP
.br
\fC#include <QMainWindow>\fP
.br
\fC#include <QApplication>\fP
.br
\fC#include <QGraphicsView>\fP
.br
\fC#include <QGraphicsPixmapItem>\fP
.br
\fC#include <stdio\&.h>\fP
.br
\fC#include <iostream>\fP
.br
\fC#include <QMessageBox>\fP
.br
\fC#include <QLabel>\fP
.br
\fC#include <string>\fP
.br
\fC#include <QImage>\fP
.br
\fC#include <QPixmap>\fP
.br
\fC#include <QDesktopWidget>\fP
.br
\fC#include <QStyle>\fP
.br
\fC#include <Qt>\fP
.br
\fC#include <QtMath>\fP
.br
\fC#include <QEvent>\fP
.br
\fC#include <QMouseEvent>\fP
.br
\fC#include <QPaintEvent>\fP
.br
\fC#include <QPen>\fP
.br
\fC#include <QBrush>\fP
.br
\fC#include <QColor>\fP
.br
\fC#include <QPoint>\fP
.br
\fC#include <vector>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBundoArr\fP"
.br
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBTRUE\fP   1"
.br
.RI "\fIincludes most of the global librarys and variables that are called in every function \fP"
.ti -1c
.RI "#define \fBFALSE\fP   0"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "int \fBopened\fP"
.br
.ti -1c
.RI "QString \fBfilename\fP"
.br
.ti -1c
.RI "int \fBscreenheight\fP"
.br
.ti -1c
.RI "int \fBscreenwidth\fP"
.br
.ti -1c
.RI "QImage \fBloadedImage\fP"
.br
.ti -1c
.RI "QImage \fBscaledImage\fP"
.br
.ti -1c
.RI "double \fBpicsize\fP"
.br
.ti -1c
.RI "int \fBcurrentImageNumber\fP"
.br
.ti -1c
.RI "int \fBisblank\fP"
.br
.ti -1c
.RI "bool \fBpen\fP"
.br
.ti -1c
.RI "bool \fBeraser\fP"
.br
.ti -1c
.RI "bool \fBbrush\fP"
.br
.ti -1c
.RI "bool \fBtext\fP"
.br
.ti -1c
.RI "bool \fBdrawing\fP"
.br
.ti -1c
.RI "QPoint \fBpointxy\fP"
.br
.ti -1c
.RI "QPoint \fBpointxy2\fP"
.br
.ti -1c
.RI "QPen \fBthePen\fP"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define FALSE   0"

.PP
Definition at line 35 of file includes\&.h\&.
.SS "#define TRUE   1"

.PP
includes most of the global librarys and variables that are called in every function General header 
.PP
Definition at line 34 of file includes\&.h\&.
.SH "Variable Documentation"
.PP 
.SS "bool brush"

.PP
Definition at line 38 of file main\&.cpp\&.
.SS "int currentImageNumber"

.PP
Definition at line 33 of file main\&.cpp\&.
.SS "bool drawing"

.PP
Definition at line 36 of file main\&.cpp\&.
.SS "bool eraser"

.PP
Definition at line 37 of file main\&.cpp\&.
.SS "QString filename"

.PP
Definition at line 27 of file main\&.cpp\&.
.SS "int isblank"

.PP
Definition at line 34 of file main\&.cpp\&.
.SS "QImage loadedImage"

.PP
Definition at line 30 of file main\&.cpp\&.
.SS "int opened"

.PP
Definition at line 26 of file main\&.cpp\&.
.SS "bool pen"

.PP
Definition at line 35 of file main\&.cpp\&.
.SS "double picsize"

.PP
Definition at line 32 of file main\&.cpp\&.
.SS "QPoint pointxy"

.PP
Definition at line 41 of file main\&.cpp\&.
.SS "QPoint pointxy2"

.PP
Definition at line 42 of file main\&.cpp\&.
.SS "QImage scaledImage"

.PP
Definition at line 31 of file main\&.cpp\&.
.SS "int screenheight"

.PP
Definition at line 28 of file main\&.cpp\&.
.SS "int screenwidth"

.PP
Definition at line 29 of file main\&.cpp\&.
.SS "bool text"

.PP
Definition at line 39 of file main\&.cpp\&.
.SS "QPen thePen"

.PP
Definition at line 43 of file main\&.cpp\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Fotoshop from the source code\&.
