.TH "C:/Users/ledio_000/Documents/GitHub/CS340/Fotoshop/mainwindow.cpp" 3 "Sat Nov 30 2013" "Fotoshop" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/ledio_000/Documents/GitHub/CS340/Fotoshop/mainwindow.cpp \- 
.PP
holds the code that is initially run to output the first GUI window  

.SH SYNOPSIS
.br
.PP
\fC#include 'mainwindow\&.h'\fP
.br
\fC#include 'ui_mainwindow\&.h'\fP
.br
\fC#include 'workingwindow\&.h'\fP
.br
\fC#include <direct\&.h>\fP
.br

.SH "Detailed Description"
.PP 
holds the code that is initially run to output the first GUI window 


.PP
Definition in file \fBmainwindow\&.cpp\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Fotoshop from the source code\&.
