.TH "C:/Users/ledio_000/Documents/GitHub/CS340/Fotoshop/mainwindow.h" 3 "Sat Nov 30 2013" "Fotoshop" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/ledio_000/Documents/GitHub/CS340/Fotoshop/mainwindow.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'workingwindow\&.h'\fP
.br
\fC#include 'includes\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBMainWindow\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "\fBUi\fP"
.br
.RI "\fIthe header file for the small new / load / close window \fP"
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Fotoshop from the source code\&.
