.TH "MainWindow" 3 "Sat Nov 30 2013" "Fotoshop" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MainWindow \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <mainwindow\&.h>\fP
.PP
Inherits QMainWindow\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBMainWindow\fP (QWidget *parent=0)"
.br
.ti -1c
.RI "\fB~MainWindow\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 12 of file mainwindow\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "MainWindow::MainWindow (QWidget *parent = \fC0\fP)\fC [explicit]\fP"

.PP
Definition at line 7 of file mainwindow\&.cpp\&.
.SS "MainWindow::~MainWindow ()"

.PP
Definition at line 14 of file mainwindow\&.cpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Fotoshop from the source code\&.
