.TH "Ui" 3 "Sat Nov 30 2013" "Fotoshop" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Ui \- 
.PP
the header file for the small new / load / close window  

.SH SYNOPSIS
.br
.PP
.SH "Detailed Description"
.PP 
the header file for the small new / load / close window 

\fBMainWindow\fP 
.SH "Author"
.PP 
Generated automatically by Doxygen for Fotoshop from the source code\&.
