.TH "C:/Users/ledio_000/Documents/GitHub/CS340/Fotoshop/workingwindow.cpp" 3 "Sat Nov 30 2013" "Fotoshop" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/ledio_000/Documents/GitHub/CS340/Fotoshop/workingwindow.cpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'workingwindow\&.h'\fP
.br
\fC#include 'ui_workingwindow\&.h'\fP
.br
\fC#include 'filters\&.h'\fP
.br
\fC#include 'darkroom\&.h'\fP
.br

.SH "Author"
.PP 
Generated automatically by Doxygen for Fotoshop from the source code\&.
