.TH "C:/Users/ledio_000/Documents/GitHub/CS340/Fotoshop/workingwindow.h" 3 "Sat Nov 30 2013" "Fotoshop" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/ledio_000/Documents/GitHub/CS340/Fotoshop/workingwindow.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'includes\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBworkingwindow\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "\fBUi\fP"
.br
.RI "\fIthe header file for the small new / load / close window \fP"
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "\fBundoArr\fP * \fBundofunc\fP"
.br
.RI "\fIHeader file for the window that opens the image and the work area\&. \fP"
.ti -1c
.RI "std::vector< QImage > \fBundoVector\fP"
.br
.ti -1c
.RI "double \fBmyInputSize\fP"
.br
.in -1c
.SH "Variable Documentation"
.PP 
.SS "double myInputSize"

.PP
Definition at line 45 of file main\&.cpp\&.
.SS "\fBundoArr\fP* undofunc"

.PP
Header file for the window that opens the image and the work area\&. Working Window 
.PP
Definition at line 40 of file main\&.cpp\&.
.SS "std::vector<QImage> undoVector"

.PP
Definition at line 47 of file main\&.cpp\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Fotoshop from the source code\&.
